/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.userregnewconti;
import org.junit.Test;
import org.junit.Assert;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test 
    public void givenFirstName_WhenProper_ReturnTrue() {
    	UserRegTest user = new UserRegTest();
        boolean result = user.checkFname("Kirti");
        Assert.assertEquals("true",result);
    }
}
